---
abstract: 'Catalyst Development Tools'
author:
  - 'Catalyst Contributors, see Catalyst.pm'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Devel
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.7000
  Catalyst::Action::RenderView: 0.04
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0.16
  Class::Accessor::Fast: 0
  Config::General: 2.42
  File::ChangeNotify: 0.02
  File::Copy::Recursive: 0
  Module::Install: 0.64
  Path::Class: 0.09
  Template: 2.14
  parent: 0
resources:
  IRC: irc://irc.perl.org/#catalyst
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/catalyst
  homepage: http://dev.catalyst.perl.org/
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Devel/
version: 1.14_01
