---
abstract: 'Catalyst Development Tools'
author:
  - 'Catalyst Contributors, see Catalyst.pm'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Fatal: 0.003
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Devel
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Catalyst: 5.90001
  Catalyst::Action::RenderView: 0.10
  Catalyst::Plugin::ConfigLoader: 0.30
  Catalyst::Plugin::Static::Simple: 0.28
  Config::General: 2.42
  File::ChangeNotify: 0.07
  File::Copy::Recursive: 0
  File::ShareDir: 0
  Module::Install: 0.91
  Moose: 0
  MooseX::Daemonize: 0
  MooseX::Emulate::Class::Accessor::Fast: 0
  Path::Class: 0.09
  Starman: 0
  Template: 2.14
  namespace::autoclean: 0
  namespace::clean: 0
resources:
  IRC: irc://irc.perl.org/#catalyst
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/catalyst
  homepage: http://dev.catalyst.perl.org/
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/catagits/Catalyst-Devel.git
version: 1.34
