abstract: Catalyst Development Tools
author: The Catalyst Core Team - see http://catalyst.perl.org/
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: Catalyst-Devel
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.7000
  Catalyst::Action::RenderView: 0.04
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0.14
  Class::Accessor::Fast: 0
  File::Copy::Recursive: 0
  Module::Install: 0.63
  Path::Class: 0.09
  Template: 2.14
  YAML: 0.55
  perl: 5.8.1
version: 1.00
