---
abstract: 'Catalyst Development Tools'
author:
  - 'Catalyst Contributors, see Catalyst.pm'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Devel
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.7000
  Catalyst::Action::RenderView: 0.04
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0.16
  Class::Accessor::Fast: 0
  Config::General: 0
  File::Copy::Recursive: 0
  Module::Install: 0.64
  Path::Class: 0.09
  Template: 2.14
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.12
